# Generated by Django 4.2.7 on 2023-11-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_created_at'),
        ('tests', '0003_test_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
