# Generated by Django 3.2.23 on 2023-12-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20231224_2203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_alter_test_the_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.CharField(max_length=50, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='choices',
            field=models.IntegerField(verbose_name='Кол-во ответов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.IntegerField(verbose_name='Кол-во вопросов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(default='Новый тест', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='test',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
