# Generated by Django 4.2.7 on 2023-12-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='Новый тест', max_length=50, verbose_name='Название')),
                ('questions', models.IntegerField(verbose_name='Кол-во вопросов')),
                ('choices', models.IntegerField(verbose_name='Кол-во ответов')),
                ('answers', models.CharField(max_length=50, verbose_name='Ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Класс')),
            ],
        ),
    ]
