# Generated by Django 4.2.7 on 2023-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_test_template_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='template_img',
            field=models.CharField(default='', max_length=255, verbose_name='Шаблон'),
        ),
    ]
