# Generated by Django 4.2.7 on 2023-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='Новый класс', max_length=20)),
                ('class_number', models.IntegerField()),
                ('class_letter', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
