# Generated by Django 3.2.23 on 2023-12-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_class_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_letter',
            field=models.CharField(default='', max_length=1, verbose_name='Буква'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='Новый класс', max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_number',
            field=models.IntegerField(verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
