# Generated by Django 4.2.7 on 2023-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=255, null=True)),
                ('sheet_image', models.CharField(max_length=255, null=True)),
                ('student_answers', models.CharField(max_length=255)),
                ('result', models.IntegerField()),
                ('scanned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
