# Generated by Django 3.2.23 on 2023-12-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20231224_2203'),
        ('tests', '0005_auto_20231224_2203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='name_image',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='result',
            field=models.IntegerField(verbose_name='Кол-во баллов'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scanned_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сканирования'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_image',
            field=models.CharField(max_length=255, null=True, verbose_name='Бланк'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='student_answers',
            field=models.CharField(max_length=255, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
